### ISSUE TITLE
impl Diagnostic for Error in miette v7

### ISSUE THREAD

**Issue by jonhoo** [andrewhickman/protox#46]
Miette [recently released major version 7](https://github.com/zkat/miette/blob/main/CHANGELOG.md#700-2024-02-05) (and 6, but it was quickly bypassed).  Currently, [`protox::Error` implements `miette::Diagnostic`](https://docs.rs/protox/0.5.1/protox/struct.Error.html#impl-Diagnostic-for-Error), but for miette 5. May be worthwhile to do a major version bump that implements the v7 version of the trait. Or, alternatively, to not have miette be part of the public API so that major version bumps to miette don't require major version bumps to protox.

**Comment by andrewhickman** [comment]
Thanks for the notification! 

Out of interest, how did you notice this. Are you using the `Diagnostic` implementation?

**Comment by wngr** [comment]
We're using `protox-parse`'s API directly in our code, which also uses `miette` to handle errors internally. Thus when updating to miette v7 the compiler errored on error auto propagation.

Cheers, and thanks again for your effort here!
