### ISSUE TITLE
Parse Error: Field name same as Message/Enum Name

### ISSUE THREAD

**Issue by chasewalden** [andrewhickman/protox#57]
## Summary

There appears to be a bug in the parser. If a field name is identical to a message/enum name, the parsing fails. The official `protoc` compiler does not fail on this.

I am trying to compile  [moby/buildkit/solver/pb/ops.proto](https://github.com/moby/buildkit/blob/dc23e43dc15c14dcf1871f8cc97a6e96c8f94a2e/solver/pb/ops.proto), but `protox` fails on some of the fields. 

## Expected Behavior:

`protox` compiler has parity with official `protoc` compiler. Field names can be any valid identifier, including other message/enum type names.

## Actual Behavior:

`protox` fails to compile fields that have identical names as defined message/enum types.

### `protos/minimal.proto`
```proto
syntax = "proto3";

message Parent {
    ChildMessage ChildMessage  = 1;
    ChildEnum ChildEnum  = 2;
}

message ChildMessage {
    string field = 1;
}

enum ChildEnum {
    UNKNOWN = 0;
    A = 1;
    B = 2;
}
```

### `build.rs`
```rust
fn main() -> miette::Result<()> {
    let _ = protox::compile(
        ["protos/minimal.proto"],
        ["protos/"],
    )?;

    // ...

    Ok(())
}
```

### Output
```
❯ cargo b
# ...
error: failed to run custom build command for `...` (exit status: 1)

Caused by: 
  process didn't exit successfully: ... (exit status: 1)
  --- stderr
  Error:   × 'ChildMessage' is not a message or enum type
     ╭─[min.proto:4:5]
   3 │ message Parent {
   4 │     ChildMessage ChildMessage  = 1;
     ·     ──────┬───── ──────┬─────
     ·           │            ╰── defined here
     ·           ╰── found here
   5 │     ChildEnum ChildEnum  = 2;
     ╰────

  Error:   × 'ChildEnum' is not a message or enum type
     ╭─[min.proto:5:5]
   4 │     ChildMessage ChildMessage  = 1;
   5 │     ChildEnum ChildEnum  = 2;
     ·     ────┬──── ────┬────
     ·         │         ╰── defined here
     ·         ╰── found here
   6 │ }
     ╰────
```

I have not been able to find where the particular diagnostic is being generated from, but will file a PR if I can find and fix.

**Comment by andrewhickman** [comment]
Thanks for the report, this should be fixed by https://github.com/andrewhickman/prost-reflect/pull/100 in prost-reflect version 0.13.1

**Comment by chasewalden** [comment]
Wow. That was an insanely quick turnaround. Thanks for closing this too. I meant to backlink the other ticket, but it must have slipped my mind.
