### ISSUE TITLE
Imports resolution doesn't give a compile error for missing imports

### ISSUE THREAD

**Issue by Veetaha** [andrewhickman/protox#6]
Here is the [repository](https://github.com/Veetaha/protox-imports-bug-repro) with the reproduction of the bug. The README.md file contains the explanation, but I am going to copy it here as well.

If you run the code in the reproduction repo with

```
cargo run
```

then it will compile and run without an error, even though the protobuf declarations residing in `protobuf/` directory have a bug. The file `b.proto` uses the type defined in `a.proto`, but to be able to do this it must first import the file via

```proto
import "foo/a.proto"
```

`protox` doesn't give a compile error, but `protoc` does. If you run the following `protoc` command you'll see an error.

```bash
$ protoc foo/a.proto foo/b.proto -I ./protobuf --ruby_out=./ruby-out
foo/b.proto:7:14: "foo.a" seems to be defined in "foo/a.proto", which is not imported by "foo/b.proto".  To use it here, please add the necessary import.
```

**Comment by andrewhickman** [comment]
Thanks for the report. There are a few error cases which protox does not currently validate against (there's a list in https://github.com/andrewhickman/prost-reflect/issues/5#issuecomment-1371210334)

**Comment by andrewhickman** [comment]
Version 0.5.0 is released with a fix for this (implemented in https://github.com/andrewhickman/prost-reflect/pull/58)

![image](https://github.com/andrewhickman/protox/assets/19718247/97ebc277-d5c3-41c9-ab83-5f135c842362)
