### ISSUE TITLE
Docs/Example request: example for integration with `tonic_build` 

### ISSUE THREAD

**Issue by nathan-at-least** [andrewhickman/protox#7]
I'm somewhat familiar with using `tonic_build` as a black-box, and I'm looking for a way to avoid the non-rust `protoc` dependency.

The only example I see here is integrating with `prost_build` but I haven't yet figured out the relationship between `tonic_build` and `prost_build`.

The only mention of [`prost_types::FileDescriptorSet`](https://docs.rs/prost-types/0.11.9/prost_types/struct.FileDescriptorSet.html) I see in in `tonic_build` is [`tonic_build::Builder::file_descriptor_set_path`](https://docs.rs/tonic-build/latest/tonic_build/struct.Builder.html#method.file_descriptor_set_path) and that reads to me like it causes `tonic_build` to _generate_ the `FileDescriptorSet` which seems like the same purpose of `protox::compile`.

How can I integrate `protox` and `tonic_build` to enable a build free of non-rust dependencies for `tonic` server/client?

**Comment by andrewhickman** [comment]
I've not tried this with `tonic_build`, but it should be possible to write the file descriptor set to a file, set [`file_descriptor_set_path()`](https://docs.rs/tonic-build/latest/tonic_build/struct.Builder.html#method.file_descriptor_set_path) to point at it, and then set [`skip_protoc_run`](https://docs.rs/tonic-build/latest/tonic_build/struct.Builder.html#method.skip_protoc_run) to bypass the normal protoc invocation
