### ISSUE TITLE
undeclared crate or module

### ISSUE THREAD

**Issue by anndavism** [andrewhickman/protox#77]
Cargo.toml:
protox = "0.7.0"

from build.rs compile:
 use protox::{compile};
  |     ^^^^^^ use of undeclared crate or module `protox`

Are there any features that I should include?  Or potential conflicts with other library components?

**Comment by andrewhickman** [comment]
Did you add `protox` to the `[build-dependencies]` or `[dependencies]` section of Cargo.toml? To be used in a build script it will need to be a [build dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#build-dependencies)

**Comment by anndavism** [comment]
That was the issue.  Thanks.
