### ISSUE TITLE
package resolution of protox is less strict than protoc

### ISSUE THREAD

**Issue by tardyp** [andrewhickman/protox#82]
on following test repository:
https://github.com/tardyp/protox_resolution_issue

- annotations.proto

```proto

syntax = "proto3";

package foo;
import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  string owner = 50000;
}

message Foo {
  string field = 1;
}
```

- foo.proto
```proto
syntax = "proto3";

// note that this package starts with com.foo, while the other package starts with foo directly
package com.foo.bar;

import "annotations.proto";

message Bar {
    option (foo.owner) = "com.foo.bar";
    string field = 1;
    foo.Foo field2 = 2;
}
```
protoc.sh will give error

  foo.proto:10:5: "foo.Foo" is resolved to "com.foo.Foo", which is not defined. The innermost scope is searched first in name resolution. Consider using a leading '.'(i.e., ".foo.Foo") to start from the outermost scope.

I created a protoxyc.py and build.rs using protox and protobuf_codegen

The three will happily accept the incorrect protobuf files.

**Comment by andrewhickman** [comment]
Nice find, thanks for the report (and the fix!)
